export PS1='%~ %% '
export PATH=:$PATH
alias a=alias
alias g=git
alias gp='git push'
alias gl='git log'
alias gss='git status'
alias m=make
alias mcl='make clean'
alias mf='make fclean'
alias mr='make re'
alias ll='ls -la'
